version: '3'

services:
  iptables-cloudflare:
    build: ./iptables-cloudflare
    container_name: ${IPTABLES_SEVICE_NAME:-iptables-cloudflare}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
  proxy-web-auto:
    build:
      context: ./nginx-cloudflare
      args:
        NGINX_IMAGE_VERSION: ${NGINX_IMAGE_VERSION:-stable-alpine}
    # image: nginx:${NGINX_IMAGE_VERSION:-stable-alpine}
    container_name: ${NGINX_WEB_SEVICE_NAME:-proxy-web-auto}
    restart: always
    ports:
      - "${IPv4:-0.0.0.0}:${DOCKER_HTTP_:-80}:80"
      - "${IPv4:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
##      - "${IPv6:-::0}:${DOCKER_HTTP_:-80}:80"
##      - "${IPv6:-::0}:${DOCKER_HTTPS:-443}:443"
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Intermediate}
      DEFAULT_HOST: ${DEFAULT_HOST}
##      ENABLE_IPV6: "true"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  docker-gen-auto:
    image: nginxproxy/docker-gen:${DOCKER_GEN_IMAGE_VERSION:-latest}
    command: -notify-sighup ${NGINX_WEB_SEVICE_NAME:-proxy-web-auto} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN_SEVICE_NAME:-docker-gen-auto}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

networks:
  default:
    external: true
    name: ${NETWORK:-proxy}
#     external:
#       name: ${NETWORK:-proxy}
